### ISSUE TITLE
Support of Python3?

### ISSUE THREAD

**Issue by AlexKorovyansky** [cwacek/cobertura-clover-transform#1]
As I can see current version in PyPi isn't compatible with Python3. 
Am I right? Do you have plans to support Python3?

**Comment by cwacek** [comment]
Merging #3 may have made this compatible with Py3. If you're actually using it with Py3 and it's working I can update the PyPi description.

**Comment by johnthagen** [comment]
@cwacek I just ran this with Python 3.5 and `lxml` 3.5.0 and did not receive any errors.

Installing `lxml` on Windows is a pain at the moment (no official wheels), but it looks like the dependency is critical to this project, so it's not reasonable to try to remove it.

**Comment by cwacekINV** [comment]
Thanks for the info @johnthagen!

**Comment by cwacek** [comment]
Thanks for the update @johnthagen!
